PUT http://localhost:3003/api/blogs/6710efd12c145992c0f359b1
Content-Type: application/json

{
    "title": "video games and aggression and stuff",
    "author": "Tobias Greitemeyer",
    "url": "https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6790614/",
    "likes": 2

}